version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_demo
    ports:
      - 9090:9090
    volumes:
      - ./config.json:/app/config.json
